const vm = new Vue({
    el: '#alpacaForm',
    data: {
        firstName: '',
        lastName: '',
        street: '',
        state: 'MN',
        availableStates: [
        {value: 'AK', name: 'Alaska'},
        {value: 'AL', name: 'Alabama'},
        {value: 'AR', name: 'Arkansas'},
        {value: 'AZ', name: 'Arizona'},
        {value: 'CA', name: 'California'},
        {value: 'CO', name: 'Colorado'},
        {value: 'CT', name: 'Connecticut'},
        {value: 'DE', name: 'Delaware'},
        {value: 'FL', name: 'Florida'},
        {value: 'GA', name: 'Georgia'},
        {value: 'HI', name: 'Hawaii'},
        {value: 'IA', name: 'Iowa'},
        {value: 'ID', name: 'Idaho'},
        {value: 'IL', name: 'Illinois'},
        {value: 'IN', name: 'Indiana'},
        {value: 'KS', name: 'Kansas'},
        {value: 'KY', name: 'Kentucky'},
        {value: 'LA', name: 'Lousianna'},
        {value: 'MA', name: 'Massachusetts'},
        {value: 'MD', name: 'Maryland'},
        {value: 'ME', name: 'Maine'},
        {value: 'MI', name: 'Michigan'},
        {value: 'MN', name: 'Minnesota'},
        {value: 'MO', name: 'Missouri'},
        {value: 'MS', name: 'Mississippi'},
        {value: 'MT', name: 'Montana'},
        {value: 'NC', name: 'North Carolina'},
        {value: 'ND', name: 'North Dakota'},
        {value: 'NE', name: 'Nebraska'},
        {value: 'NH', name: 'New Hampshire'},
        {value: 'NJ', name: 'New Jersey'},
        {value: 'NM', name: 'New Mexico'},
        {value: 'NV', name: 'Nevada'},
        {value: 'NY', name: 'New York'},
        {value: 'OH', name: 'Ohio'},
        {value: 'OK', name: 'Oklahoma'},
        {value: 'OR', name: 'Oregon'},
        {value: 'PA', name: 'Pennsylvania'},
        {value: 'RI', name: 'Rhode Island'},
        {value: 'SC', name: 'South Carolina'},
        {value: 'SD', name: 'South Dakota'},
        {value: 'TN', name: 'Tennessee'},
        {value: 'TX', name: 'Texas'},
        {value: 'UT', name: 'Utah'},
        {value: 'VA', name: 'Virginia'},
        {value: 'VT', name: 'Vermont'},
        {value: 'WA', name: 'Washington'},
        {value: 'WI', name: 'Wisconsin'},
        {value: 'WV', name: 'West Virginia'},
        {value: 'WY', name: 'Wyoming'},
        ],

        selectedColors: [], 
        colors: [
                {name: 'White', value: 'white'},
                {name: 'Beige', value: 'beige'},
                {name: 'Fawn (light, medium, dark)', value: 'fawn'},
                {name: 'Brown (light, medium, dark)', value: 'brown'},
                {name: 'Bay Black', value: 'bay-black'},
                {name: 'True Black', value: 'true-black'},
                {name: 'Rose Grey (light, medium, dark)', value: 'rose-grey'},
                {name: 'Silver Grey (light, medium, dark)', value: 'silver-grey'},
        ],
        status: '',
    }
});